name=input("please input your name: ")
surname=input("please input your surname: ")
color=input("please input your favorite color: ")
country=input("please input your country: ")
food=input("please input your favorite food: ")
car=input("please input you favorite car: ")
sport=input("please input your favorite sport: ")
print("my name is "+name)
print("my surname is "+surname)
print("my favorite color is "+color)
print("i live in country "+country)
print("my favorite food is "+food)
print("my favorite car is "+car)
print("my favorite sport is "+sport)