print(20==20)
print(20==15)
print(20>10)
print(30>50)
print(500<20)
print(500<501)
age1=int(input("please enter your age for the youtube kids!: "))
enterage=7
print(age1<=enterage)
age2=int(input("please input your age: "))
print(age2>=18)
money=int(input("please enter your balance: "))
loptop=500
print(money>=loptop)
print(True and True)
print(False and False)
print(True and False)
print(True or True)
print(False or False)
print(False or True)